INSERT INTO Authors (name, addr) VALUES ('Jack London', 'San Francisco, CA');
INSERT INTO Authors (name, addr) VALUES ('J. R. R. Tolkien', 'Bournemouth, England');
INSERT INTO Authors (name, addr) VALUES ('Leo Tolstoy', 'Astapovo, Russia');
INSERT INTO Authors (name, addr) VALUES ('Harper Lee', 'Monroeville, Alabama');
INSERT INTO Authors (name, addr) VALUES ('Stephen King', 'Portland, Maine');
INSERT INTO Authors (name, addr) VALUES ('Margaret Atwood', 'Ottawa, Canada');
INSERT INTO Authors (name, addr) VALUES ('Jane Austen', 'Winchester, England');
INSERT INTO Authors (name, addr) VALUES ('Toni Morrison', 'NYC, US');
INSERT INTO Authors (name, addr) VALUES ('Truman Capote', 'Los Angeles, CA');
INSERT INTO Authors (name, addr) VALUES ('Frank Herbert', 'Madison, Wisconsin');
INSERT INTO Books (title, authorName, year, genre, coverType) VALUES ('Martin Eden', 'Jack London', '1909', 'Novel', 'Paperback');
INSERT INTO Books (title, authorName, year, genre, format) VALUES ('White Fang', 'Jack London', '1906', 'Adventure Fiction', 'pdf');
INSERT INTO Books (title, authorName, year, genre, coverType) VALUES ('The Lord of the Rings', 'J. R. R. Tolkien', '1954', 'Fantasy Fiction', 'Hardcover');
INSERT INTO Books (title, authorName, year, genre, format) VALUES ('Anna Karenina', 'Leo Tolstoy', '1878', 'Novel', 'pdf');
INSERT INTO Books (title, authorName, year, genre, coverType) VALUES ('War and Peace', 'Leo Tolstoy', '1869', 'Novel', 'Hardcover');
INSERT INTO Books (title, authorName, year, genre, coverType) VALUES ('To Kill a Mockingbird', 'Harper Lee', '1960', 'Novel', 'Paperback');
INSERT INTO Books (title, authorName, year, genre, format) VALUES ('The Shining', 'Stephen King', '1977', 'Horror', 'ePub');
INSERT INTO Books (title, authorName, year, genre, format) VALUES ('The Handmaids Tale', 'Margaret Atwood', '1985', 'Science Fiction', 'mobi');
INSERT INTO Books (title, authorName, year, genre, coverType) VALUES ('Pride and Prejudice', 'Jane Austen', '1813', 'Romance', 'Hardcover');
INSERT INTO Books (title, authorName, year, genre, coverType) VALUES ('Beloved', 'Toni Morrison', '1987', 'Magical Realism', 'Hardcover');
INSERT INTO Books (title, authorName, year, genre, coverType) VALUES ('In Cold Blood', 'Truman Capote', '1965', 'True Crime', 'Paperback');
INSERT INTO Books (title, authorName, year, genre, coverType) VALUES ('Dune', 'Frank Herbert', '1965', 'Science Fiction', 'Paperback');